### ISSUE TITLE
Q: Use as standalone tool to extract info?

### ISSUE THREAD

**Issue by pawamoy** [pastelsky/tsdocs#10]
Is there a way to use tsdocs from the command line to extract info from source code and output it as (for example) JSON?

I'm looking for tools that would allow me to bring support for TypeScript in mkdocs/mkdocstrings.

**Comment by Zamiell** [comment]
it uses [typedoc](https://typedoc.org/) under the hood, which has been around ~~forever~~ for a really long time.
so just clone the repo, go into the cloned directory, and then type `npx typedoc`.

**Comment by pastelsky** [comment]
Also, typedoc itself is a standard that respects the TSDoc spec. 

Also covered in the README under —
https://github.com/pastelsky/tsdocs?tab=readme-ov-file#writing-good-documentation-for-your-library

So I'm closing this for now. Feel free to open if this still doesn't work for you.
