### ISSUE TITLE
Support OpenSearch description format

### ISSUE THREAD

**Issue by iamandrewluca** [pastelsky/tsdocs#25]
> The [OpenSearch description format](https://github.com/dewitt/opensearch) can be used to describe the web interface of a search engine. This allows a website to describe a search engine for itself, so that a browser or other client application can use that search engine. OpenSearch is supported by (at least) Firefox, Edge, Safari, and Chrome. (See [Reference Material](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#reference_material) for links to other browsers' documentation.)
> – https://developer.mozilla.org/en-US/docs/Web/OpenSearch

e.g. PR: https://github.com/kachkaev/njt/pull/45
e.g. https://njt.vercel.app/opensearch.xml

PS: might look into implementing this in the next weeks

**Comment by pastelsky** [comment]
This should be easy enough, so leaving this as a good first issue for someone to help implement. 

1. We'd want to redirect to /search/docs/<package-name> 

2. We don't support partial package name searches, but might be a good idea to improve the error messaging with possible suggestions in cases of an error.
