### ISSUE TITLE
TypeDocBuildError for react-leaflet

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [pastelsky/tsdocs#29]
https://tsdocs.dev/search/docs/react-leaflet

![image](https://github.com/pastelsky/tsdocs/assets/77451351/a2603951-d717-42c5-a940-fa09dd7e9721)

**Comment by pastelsky** [comment]
Should be available now —
https://tsdocs.dev/docs/react-leaflet/4.2.1/index.html
